<?php

namespace App\Controller\Admin;

use App\Entity\Dormitory;
use App\Form\DormitoryType;
use App\Repository\DormitoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/dormitory')]
class DormitoryController extends AbstractController
{
    #[Route('/', name: 'admin/app_dormitory_index', methods: ['GET'])]
    public function index(DormitoryRepository $dormitoryRepository): Response
    {
        return $this->render('admin/dormitory/index.html.twig', [
            'dormitories' => $dormitoryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'admin/app_dormitory_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, DormitoryRepository $dormitoryRepository): Response
    {
        $dormitory = new Dormitory();
        $form = $this->createForm(DormitoryType::class, $dormitory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //$entityManager->$this->getDoctrine()->getManager();

            $file = $form['image']->getData();
            if ($file) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }
                $dormitory->setImage($fileName);

            }

            $entityManager->persist($dormitory);
            $entityManager->flush();

            return $this->redirectToRoute('app_dormitory_index', [], Response::HTTP_SEE_OTHER);
        }

        $dormitories = $dormitoryRepository->findAll();

        return $this->render('admin/dormitory/new.html.twig', [
            'dormitories' => $dormitories,
            'dormitory' => $dormitory,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'admin/app_dormitory_show', methods: ['GET'])]
    public function show(Dormitory $dormitory): Response
    {
        return $this->render('dormitory/show.html.twig', [
            'dormitory' => $dormitory,
        ]);
    }

    #[Route('/{id}/edit', name: 'admin/app_dormitory_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Dormitory $dormitory, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DormitoryType::class, $dormitory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $form['image']->getData();
            if ($file) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }
                $dormitory->setImage($fileName);

            }
            $entityManager->flush();

            return $this->redirectToRoute('admin/app_dormitory_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/dormitory/edit.html.twig', [
            'dormitory' => $dormitory,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_dormitory_delete', methods: ['POST'])]
    public function delete(Request $request, Dormitory $dormitory, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $dormitory->getId(), $request->request->get('_token'))) {
            $entityManager->remove($dormitory);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_dormitory_index', [], Response::HTTP_SEE_OTHER);
    }


     /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
